/**
 * 
 */
package main.java.com.ymymrydzh.leetcode.problems;

/**
 * @author 033172
 * @date 2019-01-14 16:49:09
 * @description Given two strings s and t which consist of only lowercase
 *              letters.
 * 
 *              String t is generated by random shuffling string s and then add
 *              one more letter at a random position.
 * 
 *              Find the letter that was added in t.
 * 
 *              Example:
 * 
 *              Input: s = "abcd" t = "abcde"
 * 
 *              Output: e
 * 
 *              Explanation: 'e' is the letter that was added.
 */
public class FindtheDifference {

	/**
	 * @param args
	 */
	public static void main(String[] args) {

	}

	public char findTheDifference(String s, String t) {
		// char[] sc = s.toCharArray();
		// char[] tc = t.toCharArray();
		// Arrays.sort(sc);
		// Arrays.sort(tc);
		// int i = 0;
		// for (; i < sc.length; i++) {
		// if (sc[i] != tc[i]) {
		// return tc[i];
		// }
		// }
		// return tc[i];

		int[] sc = new int[26];
		for (char c : s.toCharArray()) {
			sc[c - 'a']++;
		}
		int[] tc = new int[26];
		for (char c : t.toCharArray()) {
			if (tc[c - 'a'] == sc[c - 'a']) {
				return c;
			}
			tc[c - 'a']++;
		}
		return 0;
	}
}
